language: java
sudo: true
dist: trusty
jdk: oraclejdk8
cache:
  directories:
   - $HOME/google-cloud-sdk
services:
 - docker
addons:
 apt:
   packages:
     - oracle-java8-installer
before_install:
# - chmod +x mvnw
 - chmod +x ./build.sh
# - chmod +x ./install.sh
 - chmod +x ./configure.sh
 - chmod +x ./deploy.sh
# This will need to be changed to reflect the GCP project we are using.
 - openssl aes-256-cbc -K $encrypted_640783b76746_key -iv $encrypted_640783b76746_iv -in projectthreeie-296b29c9c8bd.json.enc -out projectthreeie-296b29c9c8bd.json -d
script:  
# - ./install.sh
 - gcloud auth activate-service-account --key-file=projectthreeie-296b29c9c8bd.json
 - ./configure.sh
after_success:
 - ./build.sh
 - ./deploy.sh